# Generated by Django 5.0.4 on 2024-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_created=True)),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
