# Generated by Django 5.0.4 on 2024-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='books',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
