# Generated by Django 5.0.4 on 2024-06-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_alter_books_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['id']},
        ),
    ]
